//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OnlineJobs
{
    using System;
    using System.Collections.Generic;
    
    public partial class Job
    {
        public int Id { get; set; }
        public string Job_Title { get; set; }
        public string Description { get; set; }
        public string Company { get; set; }
        public string Start_Level { get; set; }
        public decimal Salary { get; set; }
        public System.DateTime Post_Date { get; set; }
        public System.DateTime Last_Date { get; set; }
        public string User_ID { get; set; }
    
        public virtual AspNetUser AspNetUser { get; set; }
    }
}
